### ISSUE TITLE
Css Property regular expression is missing { 

### ISSUE THREAD

**Issue by ezraroi** [callumlocke/css-url-rewriter#5]
If the css property is the first one in the block, e.g:
.test {background-image:url(_____)}

The regular expression will miss it as it is expecting ';' or white space at the beginning.

I fixed it by adding { 

var cssPropertyMatcher = /[;\s{]\*?[a-zA-Z\-]+\s*\:\s*url\(\s*['"]?[^'"\)\s]+['"]?\s*\)[^;}]*/g;

**Comment by mdedetrich** [comment]
Just to let you know, there is still a corner case where this regex fails, have created a pull request based off @ezraroi to fix this problem here https://github.com/callumlocke/css-url-rewriter/pull/8

@callumlocke any chance in finally getting this stuff merged?

**Comment by callumlocke** [comment]
fixed after a huge delay, sorry
